--------------------------------------------------------------------------------
-- Up
--------------------------------------------------------------------------------

CREATE TABLE TEAM (
    ID INTEGER PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    HAS_VIDEO BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE PLAYER (
    ID INTEGER PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    TEAM_ID INT NOT NULL,
    FOREIGN KEY (TEAM_ID) REFERENCES TEAM(ID)
);

-- Insert Teams
INSERT INTO TEAM (NAME) VALUES ('Mafia Stonks');
INSERT INTO TEAM (NAME) VALUES ('Arkadia');
INSERT INTO TEAM (NAME) VALUES ('La Bonne Soupe');
INSERT INTO TEAM (NAME) VALUES ('No Life');
INSERT INTO TEAM (NAME) VALUES ('Les Belettes');
INSERT INTO TEAM (NAME) VALUES ('Ants Legions');
INSERT INTO TEAM (NAME) VALUES ('Imperium');
INSERT INTO TEAM (NAME) VALUES ('Yuurei');
INSERT INTO TEAM (NAME) VALUES ('Alkya');
INSERT INTO TEAM (NAME) VALUES ('Yosheesh');
INSERT INTO TEAM (NAME) VALUES ('ALTF4');
INSERT INTO TEAM (NAME) VALUES ('Madness Science');
INSERT INTO TEAM (NAME) VALUES ('BonTouTou');
INSERT INTO TEAM (NAME) VALUES ('Undefined');
INSERT INTO TEAM (NAME) VALUES ('Équipe 51');
INSERT INTO TEAM (NAME) VALUES ('GTA');

-- Insert Players
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('TheGuill84', 1);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('MartinPonk', 1);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('JimmyBoyyy', 1);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('HarryLafranc', 1);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('Nagatow_', 1);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('IM', 1);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('Toreya', 2);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('Lovanlyh', 2);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('Takirmm', 2);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('Namirauh', 2);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('ToukoSen', 2);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('Sycloks', 2);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('Chatnapan', 3);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('SamSammeuh', 3);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('MlleEko', 3);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('Shadoko_', 3);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('Nissoku', 3);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('KaiiTooo', 3);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('NetroxTV', 4);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('suzuzya', 4);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('Necxels', 4);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('CaptainTiag', 4);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('FOBY_', 4);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('Nofiry', 4);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('justEdible', 5);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('LordFinn', 5);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('Blackphey', 5);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('PoMalaW', 5);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('Koseki', 5);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('YuudachiFR', 5);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('Val74', 6);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('Krild', 6);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('ShiRowZ', 6);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('Obscure', 6);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('Kowtaaa', 6);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('ilyes', 6);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('_KayZe', 7);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('Math_Etoile', 7);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('airtox__', 7);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('RyUwUmaaa', 7);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('KyoDeath_', 7);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('RqiiZ_', 7);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('athommm', 8);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('mangeunpied', 8);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('TwiXzi', 8);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('maxvador03', 8);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('tahenn', 8);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('sakuurajima', 8);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('Mimou18_', 9);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('Cetyx', 9);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('MrGrasDuBide', 9);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('CyclzTTV', 9);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('Kactuuus', 9);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('Lord141', 9);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('Funhora', 10);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('Yorixx', 10);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('Ploine', 10);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('Frayn25', 10);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('Elvoracitto', 10);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('Minsqa', 11);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('Alfaca', 11);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('Zepioz', 11);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('NexanMC', 11);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('Ratman258', 11);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('Itaromi', 11);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('SombreSkyZen', 12);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('Quixti5450', 12);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('MiniGreenDino', 12);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('Wozac', 12);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('FaudarzDSayo', 12);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('Salocin_Mod', 12);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('Djouimed', 13);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('Lyvant', 13);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('Loukaysi', 13);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('DJ_MAREX', 13);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('Guirlyn', 13);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('Noci__', 13);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('NotaTouTerrain', 14);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('raamensUwU', 14);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('Blocdor666', 14);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('LightSh0ft', 14);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('WooZ84', 14);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('Termi38', 14);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('_Phobos', 15);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('Oichiro', 15);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('Clemtos', 15);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('NxKrauZ_II', 15);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('ArmyCity', 15);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('IceExpert', 15);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('LZTwincy', 16);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('Benjiinounours', 16);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('Signys', 16);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('BLAZX', 16);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('Aenot', 16);
INSERT INTO PLAYER (NAME, TEAM_ID) VALUES ('Rises', 16);

--------------------------------------------------------------------------------
-- Down
--------------------------------------------------------------------------------

DROP TABLE PLAYER;
DROP TABLE TEAM;
