version: "3.8"

services:
    server:
        build:
            context: ./server/
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        environment:
            NODE_ENV: production
        restart: always
        volumes:
            - ./server/src/db/database.db:/usr/src/app/src/db/database.db
    client:
        build:
            context: ./client/
            dockerfile: Dockerfile
        ports:
            - "5173:4173"
        restart: always
